//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MrPiattoClient.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertRestaurantOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteRestaurantOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateRestaurantOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadRestaurantOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = "http://10.0.2.2:50512/WebService1.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertRestaurantCompletedEventHandler InsertRestaurantCompleted;
        
        /// <remarks/>
        public event DeleteRestaurantCompletedEventHandler DeleteRestaurantCompleted;
        
        /// <remarks/>
        public event UpdateRestaurantCompletedEventHandler UpdateRestaurantCompleted;
        
        /// <remarks/>
        public event ReadRestaurantCompletedEventHandler ReadRestaurantCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertRestaurant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertRestaurant(string mail, string password, bool confirmation) {
            object[] results = this.Invoke("InsertRestaurant", new object[] {
                        mail,
                        password,
                        confirmation});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertRestaurantAsync(string mail, string password, bool confirmation) {
            this.InsertRestaurantAsync(mail, password, confirmation, null);
        }
        
        /// <remarks/>
        public void InsertRestaurantAsync(string mail, string password, bool confirmation, object userState) {
            if ((this.InsertRestaurantOperationCompleted == null)) {
                this.InsertRestaurantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertRestaurantOperationCompleted);
            }
            this.InvokeAsync("InsertRestaurant", new object[] {
                        mail,
                        password,
                        confirmation}, this.InsertRestaurantOperationCompleted, userState);
        }
        
        private void OnInsertRestaurantOperationCompleted(object arg) {
            if ((this.InsertRestaurantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertRestaurantCompleted(this, new InsertRestaurantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteRestaurant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteRestaurant(int id) {
            object[] results = this.Invoke("DeleteRestaurant", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteRestaurantAsync(int id) {
            this.DeleteRestaurantAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteRestaurantAsync(int id, object userState) {
            if ((this.DeleteRestaurantOperationCompleted == null)) {
                this.DeleteRestaurantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteRestaurantOperationCompleted);
            }
            this.InvokeAsync("DeleteRestaurant", new object[] {
                        id}, this.DeleteRestaurantOperationCompleted, userState);
        }
        
        private void OnDeleteRestaurantOperationCompleted(object arg) {
            if ((this.DeleteRestaurantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteRestaurantCompleted(this, new DeleteRestaurantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateRestaurant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateRestaurant(int id, string mail, string password, bool confirmation) {
            object[] results = this.Invoke("UpdateRestaurant", new object[] {
                        id,
                        mail,
                        password,
                        confirmation});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateRestaurantAsync(int id, string mail, string password, bool confirmation) {
            this.UpdateRestaurantAsync(id, mail, password, confirmation, null);
        }
        
        /// <remarks/>
        public void UpdateRestaurantAsync(int id, string mail, string password, bool confirmation, object userState) {
            if ((this.UpdateRestaurantOperationCompleted == null)) {
                this.UpdateRestaurantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateRestaurantOperationCompleted);
            }
            this.InvokeAsync("UpdateRestaurant", new object[] {
                        id,
                        mail,
                        password,
                        confirmation}, this.UpdateRestaurantOperationCompleted, userState);
        }
        
        private void OnUpdateRestaurantOperationCompleted(object arg) {
            if ((this.UpdateRestaurantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateRestaurantCompleted(this, new UpdateRestaurantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReadRestaurant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Restaurant ReadRestaurant(int id) {
            object[] results = this.Invoke("ReadRestaurant", new object[] {
                        id});
            return ((Restaurant)(results[0]));
        }
        
        /// <remarks/>
        public void ReadRestaurantAsync(int id) {
            this.ReadRestaurantAsync(id, null);
        }
        
        /// <remarks/>
        public void ReadRestaurantAsync(int id, object userState) {
            if ((this.ReadRestaurantOperationCompleted == null)) {
                this.ReadRestaurantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadRestaurantOperationCompleted);
            }
            this.InvokeAsync("ReadRestaurant", new object[] {
                        id}, this.ReadRestaurantOperationCompleted, userState);
        }
        
        private void OnReadRestaurantOperationCompleted(object arg) {
            if ((this.ReadRestaurantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadRestaurantCompleted(this, new ReadRestaurantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Restaurant {
        
        private int idrestaurantField;
        
        private string mailField;
        
        private string passwordField;
        
        private bool confirmationField;
        
        private System.Nullable<System.DateTime> lastLoginField;
        
        private string nameField;
        
        private TimeSpan openingTimeField;
        
        private TimeSpan closingTimeField;
        
        private string descriptionField;
        
        private string addressField;
        
        private string phoneField;
        
        private string dressField;
        
        private System.Nullable<double> priceField;
        
        private System.Nullable<double> scoreField;
        
        private System.Nullable<int> severityLevelField;
        
        /// <remarks/>
        public int Idrestaurant {
            get {
                return this.idrestaurantField;
            }
            set {
                this.idrestaurantField = value;
            }
        }
        
        /// <remarks/>
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastLogin {
            get {
                return this.lastLoginField;
            }
            set {
                this.lastLoginField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TimeSpan OpeningTime {
            get {
                return this.openingTimeField;
            }
            set {
                this.openingTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TimeSpan ClosingTime {
            get {
                return this.closingTimeField;
            }
            set {
                this.closingTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Dress {
            get {
                return this.dressField;
            }
            set {
                this.dressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SeverityLevel {
            get {
                return this.severityLevelField;
            }
            set {
                this.severityLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TimeSpan {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void InsertRestaurantCompletedEventHandler(object sender, InsertRestaurantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertRestaurantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertRestaurantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void DeleteRestaurantCompletedEventHandler(object sender, DeleteRestaurantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteRestaurantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteRestaurantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateRestaurantCompletedEventHandler(object sender, UpdateRestaurantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateRestaurantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateRestaurantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReadRestaurantCompletedEventHandler(object sender, ReadRestaurantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadRestaurantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadRestaurantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Restaurant Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Restaurant)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591